# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- mlz-azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: $(CAzureConnection)
  GServiceConnectionName: $(GAzureConnection)
  
jobs:
- job: bicepCommercialCloud
  steps:
  - task: AzureCLI@2
    displayName: "Commercial Cloud Deployments Bicep"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub what-if \
          --name $(bDeploymentName) \
          --location $(Location) \
          --template-file $(TemplateFile)
          --result-format

- job: bicepGovCloud
  steps:  
  - task: AzureCLI@2
    displayName: "Gov Cloud Deployments Bicep"
    inputs:
      azureSubscription: $(GServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub what-if \
          --name $(bDeploymentName) \
          --location $(GLocation) \
          --template-file $(TemplateFile)
          --result-format

- job: CommercialCloud_TF
  steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.0.8'
    - task: AzureCLI@2
      displayName: "Commercial Cloud Deployments Terraform"
      inputs:
            azureSubscription: 'CAzureConnection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            addSpnToEnvironment: true
            inlineScript: |
               export ARM_CLIENT_ID=$(ClientId) `
               export ARM_CLIENT_SECRET=$(ClientSecret1) `
               export ARM_SUBSCRIPTION_ID=$(subId) `
               export ARM_TENANT_ID=$(tenantId) `
               terraform init         
               terraform plan  -var "hub_subid=$(subid)"  -input=false      
            workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform/mlz'
            
           
- job: GovCloud_TF
  steps:
   
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.0.8'
    - task: AzureCLI@2
      inputs:
            azureSubscription: 'GAzureConnection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            addSpnToEnvironment: true
            inlineScript: |
               export ARM_CLIENT_ID=$(GClientId) `
               export ARM_CLIENT_SECRET=$(GClientSecret) `
               export ARM_SUBSCRIPTION_ID=$(GSubId) `
               export ARM_TENANT_ID=$(GTenantId) `
               terraform init         
               terraform plan  -var "hub_subid=$(GSubid)"  -input=false      
            workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform/mlz'

