# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.


pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: $(CAzureConnection)  
  

jobs:
- job: bicepCommercialCloud
  steps:
  - task: AzureCLI@2
    displayName: "Deploy MLZ Bicep"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub create \
          --name $(bDeploymentName) \
          --location $(Location) \
          --template-file $(TemplateFile)
    enabled: false
  - task: AzureCLI@2
    displayName: "Extract Values and Hydrate Variables for T3 Deployment"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        deploymentoutput=$(az deployment sub show \
        --name $(bDeploymentName) \
        --query '{
        hubSubscriptionId:properties.outputs.hub.value.subscriptionId,
        hubResourceGroupName:properties.outputs.hub.value.resourceGroupName,
        hubVirtualNetworkName:properties.outputs.hub.value.virtualNetworkName,
        hubVirtualNetworkResourceId:properties.outputs.hub.value.virtualNetworkResourceId,
        logAnalyticsWorkspaceResourceId:properties.outputs.logAnalyticsWorkspaceResourceId.value,
        firewallPrivateIPAddress:properties.outputs.firewallPrivateIPAddress.value }' -o json)        
        hubSubId=$(echo $deploymentoutput|jq -r '.hubSubscriptionId') && echo "##vso[task.setvariable variable=hubSubscriptionId;]$hubSubId" 
        hubRGroupName=$(echo $deploymentoutput | jq -r '.hubResourceGroupName') && echo "##vso[task.setvariable variable=hubResourceGroupName;]$hubRGroupName"
        hubVNetworkName =$(echo $deploymentoutput | jq -r '.hubVirtualNetworkName') && echo "##vso[task.setvariable variable=hubVirtualNetworkName;]$hubVNetworkName"
        hubVNetworkResourceId=$(echo $deploymentoutput | jq -r '.hubVirtualNetworkResourceId') && echo "##vso[task.setvariable variable=hubVirtualNetworkResourceId;]$hubVNetworkResourceId"
        logAWspaceResourceId =$(echo $deploymentoutput | jq -r '.logAnalyticsWorkspaceResourceId') && echo "##vso[task.setvariable variable=logAnalyticsWorkspaceResourceId;]$logAWspaceResourceId"
        firewallPrivateIP = $(echo $deploymentoutput | jq -r' .firewallPrivateIPAddress') && echo "##vso[task.setvariable variable=firewallPrivateIPAddress;]$firewallPrivateIP"
        
        
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
            echo $(hubSubscriptionId)
            echo $(hubResourceGroupName)
            echo $(hubVirtualNetworkName)
            echo $(hubVirtualNetworkResourceId)
            echo $(logAnalyticsWorkspaceResourceId)
            echo $(firewallPrivateIPAddress)
            echo $(workloadName)
  
  - task: AzureCLI@2
    displayName: "T3 Deployment"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub create \
           --subscription $(workloadSubId) \
           --location $(Location) \
           --name $(workloadName) \
           --template-file $(T3TemplateFile) \
           --parameters \
              workloadName=$(workloadName) \
              hubSubscriptionId=$(hubSubscriptionId) \
              hubResourceGroupName=$(hubResourceGroupName) \
              hubVirtualNetworkName=$(hubVirtualNetworkName) \
              hubVirtualNetworkResourceId=$(hubVirtualNetworkResourceId) \
              logAnalyticsWorkspaceResourceId=$(logAnalyticsWorkspaceResourceId) \
              firewallPrivateIPAddress=$(firewallPrivateIPAddress)
    enabled: false

  - task: AzureCLI@2
    displayName: "Clean up Subscription Diagnostics Settings"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az monitor diagnostic-settings subscription list --query "value[? contains(@.name, ''$1'')].name" -o table  |grep ''mlz''| awk ''{system(" az monitor diagnostic-settings  delete  --resource  ''"/subscriptions/$(subId)"'' --name "$1)}'''
    enabled: false
  - task: AzureCLI@2
    displayName: "Clean up Resources"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group list -o table | grep ''mlz'' | awk ''{system("az group delete -y --no-wait -g "$1)}'''
    enabled: false

