# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

schedules:

  - cron: "0 4 * * *"
    displayName: "Nightly - mlz bicep azure cloud"
    branches:
      include:
        - main
    always: true

pool:

  vmImage: ubuntu-latest

jobs:

- job: bicepCommercialCloud
  displayName: "Nightly deployment of Mission LZ Bicep on AzureCloud"

  steps:

  - template: templates/az-deployment.yml
    parameters:
      ServiceConnectionName: $(CAzureConnection)
      DeploymentName: $(bDeploymentName)
      Location: $(CLocation)
      WorkloadSubId: $(CSubId)
      WorkloadName: $(workloadName)

  - template: templates/clean-az-subscription.yml
    parameters:
      serviceConnectionName: $(CAzureConnection)
