# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

schedules:
  - cron: "0 2 * * *"
    displayName: "Nightly - mlz Terraform azure cloud"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

jobs:
- job: CommercialCloud_TF
  steps:
  - task: TerraformInstaller@0
    inputs:
        terraformVersion: 'latest'

  - template: templates/apply-tf.yml
    parameters:
      ServiceConnectionName: $(CAzureConnection)
      ClientId: $(ClientId)
      ClientSecret: $(ClientSecret)
      SubscriptionId: $(CSubId)
      TenantId: $(CTenantId)
      Environment: $(CCloudEnv)
      MetadataHost: $(CMetadataHost)
      Location: $(CLocation)

  - template: templates/clean-az-subscription.yml
      parameters:
      serviceConnectionName: $(CAzureConnection)
