 # Copyright (c) Microsoft Corporation. 
 # Licensed under the MIT License.

schedules:
  - cron: "0 3 * * *"
    displayName: "Nightly - mlz Terraform azure cloud" 
    branches:
      include:
        - main


pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: $(CAzureConnection)
  
jobs:
- job: CommercialCloud_TF
  steps:
  - task: TerraformInstaller@0
    inputs:
        terraformVersion: '1.0.8'
  - task: AzureCLI@2
    displayName: "Deploy MLZ Terraform"
    inputs:
            azureSubscription: $(CAzureConnection)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            addSpnToEnvironment: true
            inlineScript: |
               export ARM_CLIENT_ID=$(ClientId) `
               echo `
               export ARM_CLIENT_SECRET=$(ClientSecret) `
               echo `
               export ARM_SUBSCRIPTION_ID=$(subId) `
               echo `
               export ARM_TENANT_ID=$(tenantId) `
               echo `
               terraform init         
               terraform plan  -var "hub_subid=$(subid)"  -input=false      
               terraform apply -var "hub_subid=$(subid)" -auto-approve -input=false
            workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform/mlz'
            useGlobalConfig: true
    continueOnError: true
  - task: AzureCLI@2
    displayName: "Teardown MLZ Terraform"
    inputs:
            azureSubscription: $(CAzureConnection)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            addSpnToEnvironment: true
            inlineScript: |
               export ARM_CLIENT_ID=$(ClientId) `
               echo `
               export ARM_CLIENT_SECRET=$(ClientSecret) `
               echo `
               export ARM_SUBSCRIPTION_ID=$(subId) `
               echo `
               export ARM_TENANT_ID=$(tenantId) `
               echo `
               terraform init         
               terraform destroy -var "hub_subid=$(subid)" -auto-approve -input=false
            workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform/mlz'
            useGlobalConfig: true

