# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

schedules:
  - cron: "0 2 * * *"
    displayName: "Nightly - mlz Terraform azure US Gov cloud"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

jobs:
- job: GovCloud_TF
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - template: templates/apply-tf.yml
    parameters:
      ServiceConnectionName: $(GAzureConnection)
      ClientId: $(GClientId)
      ClientSecret: $(GClientSecret)
      SubscriptionId: $(GSubId)
      TenantId: $(GTenantId)
      Environment: $(GCloudEnv)
      MetadataHost: $(GMetadataHost)
      Location: $(GLocation)

  - template: templates/clean-az-subscription.yml
    parameters:
      serviceConnectionName: $(GAzureConnection)
