# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# disable CI per:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#disabling-the-ci-trigger
trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

jobs:

- job: CommercialCloud_TF
  displayName: "PR Checks for Mission LZ Terraform on AzureCloud"

  steps:
  - template: templates/terraform-plan.yml
    parameters:
      ServiceConnectionName: $(CAzureConnection)
      ClientId: $(ClientId)
      ClientSecret: $(ClientSecret)
      SubscriptionId: $(CSubId)
      TenantId: $(CTenantId)
      Environment: $(CCloudEnv)
      MetadataHost: $(CMetadataHost)
      Location: $(CLocation)
