# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# disable CI per:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#disabling-the-ci-trigger
trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: $(CAzureConnection)

jobs:
- job: bicepCommercialCloud
  steps:
  - checkout: self
    persistCredentials: true
  - task: AzureCLI@2
    displayName: "What-if Bicep"
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        datetime=$(date +%s) # gets the current date time as an epoch
        az deployment sub what-if \
          --name $(bDeploymentName) \
          --location $(Location) \
          --template-file $(TemplateFile) \
          --parameters resourcePrefix=$datetime

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generate SBOM'
    inputs:
      BuildComponentPath: '$(Build.ArtifactStagingDirectory)'
      BuildDropPath: '$(Build.SourcesDirectory)'
      PackageName: 'TestPackage'
      PackageVersion: '2.1.11'      
    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
            git config --global user.email "bsailesh@msn.com"
            git config --global user.name "Vidya Bala"
            git checkout -t self;
            git update '_manifest/*';
            git status;
            whoami;
            git push origin master
            git commit -m "Retrieved latest Developer SB changes!"
            echo "Pushing now!!!";
            git push --set-upstream self;
      workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Git Commit and Tag from pipeline'
    continueOnError: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish SBOM to Build Artifact'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/_manifest'
      ArtifactName: 'drop'
      publishLocation: 'Container'