# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
- main
- mlz-azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  GServiceConnectionName: $(GAzureConnection)

jobs:
- job: GovCloud_TF
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.0.8'
  - task: AzureCLI@2
    displayName: "Deploy MLZ Terraform"
    inputs:
      azureSubscription: $(GAzureConnection)
      scriptType: 'bash'
      addSpnToEnvironment: true
      scriptLocation: 'inlineScript'
      inlineScript: |
          export ARM_CLIENT_ID=$(GClientId)
          export ARM_CLIENT_SECRET=$(GClientSecret)
          export ARM_SUBSCRIPTION_ID=$(GSubId)
          export ARM_TENANT_ID=$(GTenantId)
          export ARM_ENVIRONMENT=$(CloudEnv)
          terraform init
          terraform plan -var "hub_subid=$(GSubid)" -var metadata_host=$(MetadataHost) -var environment=$(CloudEnv) -var location=$(GLocation) -input=false
      workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform/mlz'
      useGlobalConfig: true
