# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
- main
- mlz-azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  GServiceConnectionName: $(GAzureConnection)
  
jobs:
- job: bicepGovCloud
  steps:
  - task: AzureCLI@2
    displayName: "Deploy MLZ Bicep"
    inputs:
      azureSubscription: $(GServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub what-if \
          --name $(bDeploymentName) \
          --location $(GLocation) \
          --template-file $(TemplateFile)
