# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# disable CI per:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#disabling-the-ci-trigger
trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  GServiceConnectionName: $(GAzureConnection)
  
jobs:
- job: bicepGovCloud
  steps:
  - task: AzureCLI@2
    displayName: "What-if Bicep"
    inputs:
      azureSubscription: $(GServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        datetime=$(date +%s) # gets the current date time as an epoch
        az deployment sub what-if \
          --name $(bDeploymentName) \
          --location $(GLocation) \
          --template-file $(TemplateFile) \
          --parameters resourcePrefix=$datetime
