# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

parameters:

- name: ServiceConnectionName
  type: string
- name: DeploymentName
  type: string
- name: Location
  type: string
- name: WorkloadSubId
  type: string
- name: WorkloadName
  type: string

steps:

  - task: AzureCLI@2
    displayName: "Deploy MLZ Bicep"
    inputs:
      azureSubscription: ${{ parameters.ServiceConnectionName }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        datetime=$(date +%s) # gets the current date time as an epoch
        az deployment sub create \
          --name ${{ parameters.DeploymentName }} \
          --location ${{ parameters.Location }} \
          --template-file $(Build.SourcesDirectory)/src/bicep/mlz.bicep \
          --parameters resourcePrefix=$datetime

  - task: AzureCLI@2
    displayName: "Generate deploymentVariables.json for all addons and examples"
    inputs:
      azureSubscription: ${{ parameters.ServiceConnectionName }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub show \
          --name ${{ parameters.DeploymentName }} \
          --query properties.outputs \
          > $(Build.SourcesDirectory)/src/bicep/examples/deploymentVariables.json

  - task: AzureCLI@2
    displayName: "T3 Bicep Deployment"
    inputs:
      azureSubscription: ${{ parameters.ServiceConnectionName }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        datetime=$(date +%s) # gets the current date time as an epoch
        az deployment sub create \
           --subscription ${{ parameters.WorkloadSubId }} \
           --location ${{ parameters.Location }} \
           --name ${{ parameters.WorkloadName }} \
           --template-file $(Build.SourcesDirectory)/src/bicep/add-ons/tier3/tier3.bicep \
           --parameters resourcePrefix=$datetime
