# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# This docker-compose file defines a container that runs the ez deploy application for Mission LZ.
# To run the containers:
# 1. Install Docker Desktop or Docker CE
# 2. In BASH or PowerShell, navigate to the folder containing this file.
# 3. Run this command: docker-compose up -d
version: '3.8'
services:

  webfront:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: "mlzfront"
      ports:
        - "80:80"
    