# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: validate-build-bicep
on:
  push:
    branches:
      - bicep
jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.26.1
        inlineScript: |
          az bicep build --file main.bicep