# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: validate-bicep
on: 
  pull_request:
    paths: 
    - '**.bicep'
  workflow_dispatch:
    paths:
    - '**.bicep'
jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          az bicep build --file src/bicep/mlz.bicep
